// <auto-generated />
using System;
using JCP.TicketWave.BookingService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JCP.TicketWave.BookingService.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20251202163943_InitialCreateSqlServer")]
    partial class InitialCreateSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("booking")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JCP.TicketWave.BookingService.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_bookings_created_at");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_bookings_event_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_bookings_expires_at")
                        .HasFilter("expires_at IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_bookings_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_bookings_user_id");

                    b.HasIndex("EventId", "Status")
                        .HasDatabaseName("IX_bookings_event_status");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_bookings_user_status");

                    b.ToTable("bookings", "booking");
                });

            modelBuilder.Entity("JCP.TicketWave.BookingService.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReservedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_tickets_booking_id")
                        .HasFilter("booking_id IS NOT NULL");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_tickets_event_id");

                    b.HasIndex("ReservedUntil")
                        .HasDatabaseName("IX_tickets_reserved_until")
                        .HasFilter("reserved_until IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_tickets_status");

                    b.HasIndex("EventId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_tickets_event_seat_unique")
                        .HasFilter("seat_number IS NOT NULL");

                    b.HasIndex("EventId", "Status")
                        .HasDatabaseName("IX_tickets_event_status");

                    b.HasIndex("EventId", "TicketType", "Status")
                        .HasDatabaseName("IX_tickets_event_type_status");

                    b.ToTable("tickets", "booking");
                });

            modelBuilder.Entity("JCP.TicketWave.BookingService.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("JCP.TicketWave.BookingService.Domain.Entities.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("JCP.TicketWave.BookingService.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
